services:
  maker-wallet:
    image: "${LINERA_IMAGE:-linera}"
    container_name: maker-wallet
    ports:
      - "40082:8080"
    command: [ "./wallet-entrypoint.sh" ]
    extra_hosts:
      api.lineraswap.fun: "${LAN_IP}"
      api.linerameme.fun: "${LAN_IP}"
      api.testnet-conway.lineraswap.fun: "${LAN_IP}"
      api.testnet-conway.linerameme.fun: "${LAN_IP}"
    volumes:
      - ../wallet/maker/0:/wallet
    environment:
      NO_PROXY: ${NO_PROXY}
      no_proxy: ${no_proxy}
      RUST_LOG: info
    restart: always
