services:
  kline:
    image: "kline"
    container_name: kline
    ports:
      - "25080:25080"
    command: [ "./kline-entrypoint.sh" ]
    extra_hosts:
      - "api.lineraswap.fun:${LAN_IP}"
      - "api.testnet-conway.lineraswap.fun:${LAN_IP}"
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      SWAP_APPLICATION_ID: ${SWAP_APPLICATION_ID}
      SWAP_HOST: ${SWAP_HOST}
    restart: always
